name: 🪲 Feature
description: File a feature report
title: "Feature: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: textarea
    id: description
    attributes:
      label: What is the feature about?
      description: Please provide a detailed description of the feature.
    validations:
      required: true
  - type: dropdown
    id: services
    attributes:
      label: Affected services
      description: Please select which services do you think will be impacted.
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
#  - type: dropdown
#    id: services
#    attributes:
#      label: Please select which services do you think will be impacted.
#      multiple: true
#      options:
#        - repository-service-for-tuf
#        - repository-service-for-tuf-cli
#        - repository-service-for-tuf-api
#        - repository-service-for-tuf-worker
#    validations:
#      required: true
