name: Lint

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: '3.10'

      - name: Lint
        run: |
          pip install pipenv
          pipenv install -d
          pipenv run make lint