name: Update Python dependencies
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  update-dep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install prerequisites
        run: |
          pip install tox pipenv
      - name: Update dependencies
        run: |
          pipenv shell
          pipenv update -d
          make requirements
      - name: Run tests
        run: |
          make functional-tests
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build: Update Python dependencies"
          title: "build: Update Python dependencies"
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: report, automated pr, python
